name: product-is-builder-jdk17

on:
  workflow_dispatch:
  schedule:
#    At 00:00 on day-of-month 1
    - cron:  '0 0 1 * *'


env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone product IS
        run: |
          git clone https://github.com/wso2/product-is
      - name: Set up Adopt JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Product-IS build with JDK 11 without Integration Tests
        run: |
          cd product-is/
          mvn clean install --batch-mode -Dmaven.test.skip=true | tee mvn-build.log
      - name: Minio upload
        # You may pin to the exact commit or the version.
        # uses: lovellfelix/minio-deploy-action@cfc4b36780804138fc0df64d8e862ed28db7fd34
        uses: lovellfelix/minio-deploy-action@v1.1.1
        with:
          # Minio endpoint of object storage host
          endpoint: pippo.it
          # Minio access key (username)
          access_key: aaa
          # Minio secret key (password)
          secret_key: aaaa
          # Set the target minio bucket for deployment.
          bucket: release-git
          # Set an input directory for deployment.
          source_dir: modules/distribution/target
          # Set a target directory for deployment (with a leading slash).
          target_dir: / # optional, default is /
